# Generated by Django 4.1.7 on 2023-04-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rotativo_mensalista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotativo',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observacoes'),
        ),
    ]
